Repository usanli/SWE574-G1, pull requests merged in 2025-03, with the labels that each got.

#11 Initial Frontend Setup
  .gitignore
  client/.gitignore
  client/README.md
  client/app/api/posts/route.js
  client/app/favicon.ico
  client/app/globals.css
  client/app/layout.js
  client/app/login/page.js
  client/app/page.js
  client/app/profile/page.js
  client/app/register/page.js
  client/components.json
  client/components/feed-filters.js
  client/components/navbar.js
  client/components/post-card.js
  client/components/post-feed.js
  client/components/sidebar.js
  client/components/theme-provider.js
  client/components/theme-toggle.js
  client/components/ui/badge.jsx
  client/components/ui/button.jsx
  client/components/ui/card.jsx
  client/components/ui/checkbox.jsx
  client/components/ui/dropdown-menu.jsx
  client/components/ui/input.jsx
  client/components/ui/label.jsx
  client/components/ui/separator.jsx
  client/components/ui/sheet.jsx
  client/components/ui/tabs.jsx
  client/context/auth-context.js
  client/context/feed-context.js
  client/eslint.config.mjs
  client/jsconfig.json
  client/lib/api.js
  client/lib/utils.js
  client/next.config.mjs
  client/package-lock.json
  client/package.json
  client/postcss.config.mjs
  client/public/file.svg
  client/public/globe.svg
  client/public/next.svg
  client/public/vercel.svg
  client/public/window.svg
Labels: Type: Frontend

#14 Post and Comment endpoints
  backend/app/core/database.py
  backend/app/main.py
  backend/app/models/comment_model.py
  backend/app/models/mystery_model.py
  backend/app/routers/comments.py
  backend/app/routers/mysteries.py
  backend/app/schemas/comment_schema.py
  backend/app/schemas/mystery_schema.py
  backend/app/services/comment_service.py
  backend/app/services/mystery_service.py
Labels: Priority: High, Type: Backend, Issue Type: Feature

#16 Adding further frontend functionality
  client/Dockerfile
  client/app/api/posts/[id]/comments/route.js
  client/app/api/posts/[id]/route.js
  client/app/api/posts/[id]/vote/route.js
  client/app/layout.js
  client/app/login/page.js
  client/app/page.js
  client/app/post/[id]/page.js
  client/app/profile/[username]/page.js
  client/app/register/page.js
  client/app/submit/page.js
  client/components/feed-filters.js
  client/components/navbar.js
  client/components/post-card.js
  client/components/post-comments.js
  client/components/post-details.js
  client/components/post-feed.js
  client/components/post-skeleton.js
  client/components/similar-post-card.js
  client/components/submit-form.js
  client/components/ui/accordion.jsx
  client/components/ui/alert.jsx
  client/components/ui/avatar.jsx
  client/components/ui/dialog.jsx
  client/components/ui/radio-group.jsx
  client/components/ui/scroll-area.jsx
  client/components/ui/select.jsx
  client/components/ui/skeleton.jsx
  client/components/ui/slider.jsx
  client/components/ui/switch.jsx
  client/components/ui/textarea.jsx
  client/components/user-profile.js
  client/context/auth-context.js
  client/context/feed-context.js
  client/context/search-context.js
  client/lib/api.js
  client/lib/categories.js
  client/lib/post-api.js
  client/lib/user-api.js
  client/lib/utils.js
  client/next.config.mjs
  client/package-lock.json
  client/package.json
Labels: Priority: Critical, Issue Type: Enhancement, Type: Frontend

#32 Mobile init
  client/app/globals.css
  client/app/icons-setup.js
  client/app/layout.js
  client/app/page.js
  client/app/search/loading.js
  client/app/search/page.js
  client/components/mobile-bottom-nav.js
  client/components/mobile-install-prompt.js
  client/eslint.config.mjs
  client/next.config.mjs
  client/package-lock.json
  client/package.json
  client/public/icons/icon-128x128.png
  client/public/icons/icon-144x144.png
  client/public/icons/icon-152x152.png
  client/public/icons/icon-192x192.png
  client/public/icons/icon-256x256.png
  client/public/icons/icon-384x384.png
  client/public/icons/icon-48x48.png
  client/public/icons/icon-512x512.png
  client/public/icons/icon-72x72.png
  client/public/icons/icon-96x96.png
  client/public/icons/maskable-icon.png
  client/public/manifest.json
  client/public/screenshots/.gitkeep
  client/public/screenshots/create-screenshots.js
  client/public/screenshots/desktop-home.png
  client/public/screenshots/desktop-post.png
  client/public/screenshots/mobile-home.png
  client/public/screenshots/mobile-post.png
  client/public/sw.js
  client/public/workbox-e43f5367.js
  client/tailwind.config.js
Labels: Issue Type: Enhancement, Type: Frontend

#35 Update README.md with run instructions
  README.md
Labels: Issue Type: Documentation

#39 Mobile fix
  client/package-lock.json
  client/package.json
  client/public/screenshots/create-screenshots.js
  client/public/sw.js
  client/public/workbox-4754cb34.js
  client/public/workbox-e43f5367.js
Labels: Issue Type: Bug

#33 Backend-Frontend Integration
  backend/app/core/database.py
  backend/app/main.py
  backend/app/models/comment_model.py
  backend/app/models/vote_model.py
  backend/app/routers/comments.py
  backend/app/routers/votes.py
  backend/app/schemas/comment_schema.py
  backend/app/services/comment_service.py
  client/Dockerfile
  client/app/api/posts/[id]/comments/route.js
  client/app/api/posts/[id]/route.js
  client/app/api/posts/[id]/vote/route.js
  client/app/api/posts/route.js
  client/app/login/page.js
  client/app/post/[id]/page.js
  client/app/register/page.js
  client/components/navbar.js
  client/components/post-card.js
  client/components/post-comments.js
  client/components/post-details.js
  client/components/post-feed.js
  client/components/submit-form.js
  client/components/user-profile.js
  client/context/auth-context.js
  client/lib/api-service.js
  client/lib/api.js
  client/lib/categories.js
  client/lib/post-api.js
  client/lib/user-api.js
  client/next.config.mjs
  client/package-lock.json
  client/package.json
  docker-compose.yml
Labels: Priority: High, Issue Type: Enhancement, Type: Backend, Issue Type: Bug, Type: Frontend
